name: Deploy Hexo Blog
 
on:
  push:
    branches:
      - source
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ～/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/packages-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install Dependencies
        run:  |
          npm install
          mkdir themes
          ln -s node_modules/hexo-theme-shokax themes/shokax
      - name: Build the site
        run:  npm run build
      - name: Move public folder out
        run: |
          ls public
          cat public/index.html
          mv public ../
      - name: Checkout main branch
        uses: actions/checkout@v4
        with: 
          ref: main
      - name: Move public content in
        run: |
          rm -rf *
          mv ../public/* .
      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Commit and push to main
        run: |
           if [[ -n $(git status --porcelain) ]]; then
             git add .
             git commit -m "Deploy to main branch"
             git push origin main
           else
             echo "No changes to commit"
           fi
          
