name: Deploy Hexo Blog
 
on:
  push:
    branches:
      - source
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      # - name: Install Dependencies
      #   run:  npm install
      # - name: Build
      #   run:  npm run build
      - name: Copy public folder to main branch
        run: |
          mkdir public
          echo "1112" > public/1.txt
          mv public ../
      - name: checkout main branch
        uses: actions/checkout@v4
        with: 
          ref: main
      - name: test
        run: |
          ls -a
          rm -rf *
          ls -a
          mv ../public/* .
      - name: Commit and push to main
        run: |
           if [[ -n $(git status --porcelain) ]]; then
             git add .
             git commit -m "Deploy to main branch"
             git push origin main
           else
             echo "No changes to commit"
           fi
          
