name: Deploy Hexo Blog
 
on:
  push:
    branches:
      - source
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run:  npm install
      - name: Build
        run:  npm run build
      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Copy public folder to main branch
        run: |
          git fetch origin main || git branch main
          git worktree add main main
          cp -r ./public/* main/
          cd public
          git add --all
          git commit -m "Deploy to main branch"
      - name: Commit and push to main
        run: |
          git push origin main
          
